	MKRVIDOR4000_graphics_lite_sys u0 (
		.arb_fb_clk        (<connected-to-arb_fb_clk>),        //     arb_fb.clk
		.arb_fb_rdy        (<connected-to-arb_fb_rdy>),        //           .rdy
		.arb_fb_data       (<connected-to-arb_fb_data>),       //           .data
		.arb_fb_dv         (<connected-to-arb_fb_dv>),         //           .dv
		.arb_fb_start      (<connected-to-arb_fb_start>),      //           .start
		.arb_mipi_clk      (<connected-to-arb_mipi_clk>),      //   arb_mipi.clk
		.arb_mipi_data     (<connected-to-arb_mipi_data>),     //           .data
		.arb_mipi_dv       (<connected-to-arb_mipi_dv>),       //           .dv
		.arb_mipi_start    (<connected-to-arb_mipi_start>),    //           .start
		.clk_clk           (<connected-to-clk_clk>),           //        clk.clk
		.clk_0_clk         (<connected-to-clk_0_clk>),         //      clk_0.clk
		.csi_i2c_scl_i     (<connected-to-csi_i2c_scl_i>),     //    csi_i2c.scl_i
		.csi_i2c_scl_o     (<connected-to-csi_i2c_scl_o>),     //           .scl_o
		.csi_i2c_scl_en    (<connected-to-csi_i2c_scl_en>),    //           .scl_en
		.csi_i2c_sda_i     (<connected-to-csi_i2c_sda_i>),     //           .sda_i
		.csi_i2c_sda_o     (<connected-to-csi_i2c_sda_o>),     //           .sda_o
		.csi_i2c_sda_en    (<connected-to-csi_i2c_sda_en>),    //           .sda_en
		.encoder_encoder_a (<connected-to-encoder_encoder_a>), //    encoder.encoder_a
		.encoder_encoder_b (<connected-to-encoder_encoder_b>), //           .encoder_b
		.fb_st_start       (<connected-to-fb_st_start>),       //      fb_st.start
		.fb_st_data        (<connected-to-fb_st_data>),        //           .data
		.fb_st_dv          (<connected-to-fb_st_dv>),          //           .dv
		.fb_st_ready       (<connected-to-fb_st_ready>),       //           .ready
		.fb_vport_blu      (<connected-to-fb_vport_blu>),      //   fb_vport.blu
		.fb_vport_de       (<connected-to-fb_vport_de>),       //           .de
		.fb_vport_grn      (<connected-to-fb_vport_grn>),      //           .grn
		.fb_vport_hs       (<connected-to-fb_vport_hs>),       //           .hs
		.fb_vport_vs       (<connected-to-fb_vport_vs>),       //           .vs
		.fb_vport_red      (<connected-to-fb_vport_red>),      //           .red
		.flash_spi_MOSI    (<connected-to-flash_spi_MOSI>),    //  flash_spi.MOSI
		.flash_spi_SCLK    (<connected-to-flash_spi_SCLK>),    //           .SCLK
		.flash_spi_MISO    (<connected-to-flash_spi_MISO>),    //           .MISO
		.flash_spi_CS      (<connected-to-flash_spi_CS>),      //           .CS
		.hdmi_i2c_scl_i    (<connected-to-hdmi_i2c_scl_i>),    //   hdmi_i2c.scl_i
		.hdmi_i2c_scl_o    (<connected-to-hdmi_i2c_scl_o>),    //           .scl_o
		.hdmi_i2c_scl_en   (<connected-to-hdmi_i2c_scl_en>),   //           .scl_en
		.hdmi_i2c_sda_i    (<connected-to-hdmi_i2c_sda_i>),    //           .sda_i
		.hdmi_i2c_sda_o    (<connected-to-hdmi_i2c_sda_o>),    //           .sda_o
		.hdmi_i2c_sda_en   (<connected-to-hdmi_i2c_sda_en>),   //           .sda_en
		.irq_in_port       (<connected-to-irq_in_port>),       //        irq.in_port
		.irq_out_port      (<connected-to-irq_out_port>),      //           .out_port
		.mb_ak             (<connected-to-mb_ak>),             //         mb.ak
		.mb_rq             (<connected-to-mb_rq>),             //           .rq
		.mipi_rx_clk       (<connected-to-mipi_rx_clk>),       //    mipi_rx.clk
		.mipi_rx_data      (<connected-to-mipi_rx_data>),      //           .data
		.mipi_st_data      (<connected-to-mipi_st_data>),      //    mipi_st.data
		.mipi_st_start     (<connected-to-mipi_st_start>),     //           .start
		.mipi_st_dv        (<connected-to-mipi_st_dv>),        //           .dv
		.neopixel_data     (<connected-to-neopixel_data>),     //   neopixel.data
		.neopixel_clock    (<connected-to-neopixel_clock>),    //           .clock
		.nina_spi_MOSI     (<connected-to-nina_spi_MOSI>),     //   nina_spi.MOSI
		.nina_spi_SCLK     (<connected-to-nina_spi_SCLK>),     //           .SCLK
		.nina_spi_MISO     (<connected-to-nina_spi_MISO>),     //           .MISO
		.nina_spi_CS       (<connected-to-nina_spi_CS>),       //           .CS
		.pex_pio_in        (<connected-to-pex_pio_in>),        //    pex_pio.in
		.pex_pio_dir       (<connected-to-pex_pio_dir>),       //           .dir
		.pex_pio_out       (<connected-to-pex_pio_out>),       //           .out
		.pex_pio_msel      (<connected-to-pex_pio_msel>),      //           .msel
		.qr_vid_in_data    (<connected-to-qr_vid_in_data>),    //  qr_vid_in.data
		.qr_vid_in_dv      (<connected-to-qr_vid_in_dv>),      //           .dv
		.qr_vid_in_start   (<connected-to-qr_vid_in_start>),   //           .start
		.qr_vid_in_reset   (<connected-to-qr_vid_in_reset>),   //           .reset
		.qr_vid_in_clk     (<connected-to-qr_vid_in_clk>),     //           .clk
		.qr_vid_out_data   (<connected-to-qr_vid_out_data>),   // qr_vid_out.data
		.qr_vid_out_dv     (<connected-to-qr_vid_out_dv>),     //           .dv
		.qr_vid_out_start  (<connected-to-qr_vid_out_start>),  //           .start
		.qspi_dclk         (<connected-to-qspi_dclk>),         //       qspi.dclk
		.qspi_ncs          (<connected-to-qspi_ncs>),          //           .ncs
		.qspi_oe           (<connected-to-qspi_oe>),           //           .oe
		.qspi_dataout      (<connected-to-qspi_dataout>),      //           .dataout
		.qspi_dataoe       (<connected-to-qspi_dataoe>),       //           .dataoe
		.qspi_datain       (<connected-to-qspi_datain>),       //           .datain
		.reset_reset_n     (<connected-to-reset_reset_n>),     //      reset.reset_n
		.reset_0_reset_n   (<connected-to-reset_0_reset_n>),   //    reset_0.reset_n
		.sam_pio_in        (<connected-to-sam_pio_in>),        //    sam_pio.in
		.sam_pio_dir       (<connected-to-sam_pio_dir>),       //           .dir
		.sam_pio_out       (<connected-to-sam_pio_out>),       //           .out
		.sam_pio_msel      (<connected-to-sam_pio_msel>),      //           .msel
		.sam_pwm_pwm       (<connected-to-sam_pwm_pwm>),       //    sam_pwm.pwm
		.sdram_addr        (<connected-to-sdram_addr>),        //      sdram.addr
		.sdram_ba          (<connected-to-sdram_ba>),          //           .ba
		.sdram_cas_n       (<connected-to-sdram_cas_n>),       //           .cas_n
		.sdram_cke         (<connected-to-sdram_cke>),         //           .cke
		.sdram_cs_n        (<connected-to-sdram_cs_n>),        //           .cs_n
		.sdram_dq          (<connected-to-sdram_dq>),          //           .dq
		.sdram_dqm         (<connected-to-sdram_dqm>),         //           .dqm
		.sdram_ras_n       (<connected-to-sdram_ras_n>),       //           .ras_n
		.sdram_we_n        (<connected-to-sdram_we_n>),        //           .we_n
		.vid_clk           (<connected-to-vid_clk>),           //        vid.clk
		.wm_pio_in         (<connected-to-wm_pio_in>),         //     wm_pio.in
		.wm_pio_dir        (<connected-to-wm_pio_dir>),        //           .dir
		.wm_pio_out        (<connected-to-wm_pio_out>),        //           .out
		.wm_pio_msel       (<connected-to-wm_pio_msel>)        //           .msel
	);

